perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_dk_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_dk_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_dk_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_dk_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_dk_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_dk_8h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_lt_0h.ctr_lt_0h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_lt_1h.ctr_lt_1h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_lt_2h.ctr_lt_2h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_lt_4h.ctr_lt_4h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/deseqMatchDeg.pl mydeseqHo.updn.inf_lt_8h.ctr_lt_8h.csv genes_med4phm2.tsv > mydeseqHo.updn.inf_lt_8h_vs_ctr.tsv
