perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_0h.ctr_lt_0h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_1h.ctr_lt_1h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_2h.ctr_lt_2h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_4h.ctr_lt_4h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_8h.ctr_lt_8h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_0h.ctr_lt_0h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_1h.ctr_lt_1h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_2h.ctr_lt_2h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_4h.ctr_lt_4h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_8h.ctr_lt_8h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_0h.ctr_lt_0h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_1h.ctr_lt_1h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_2h.ctr_lt_2h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_4h.ctr_lt_4h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_8h.ctr_lt_8h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_0h.ctr_lt_0h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_1h.ctr_lt_1h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_2h.ctr_lt_2h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_4h.ctr_lt_4h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_8h.ctr_lt_8h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_8h_vs_ctr.tsv

perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_dk_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_dk_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_dk_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_dk_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_dk_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_dk_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_dk_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_dk_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_dk_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_dk_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_dk_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_dk_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_dk_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_dk_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_dk_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_dk_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_dk_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_dk_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_dk_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_dk_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_dk_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_dk_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_dk_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_dk_8h_vs_ctr.tsv

perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.updn.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.up.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.dn.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.all.inf_lt_8h_vs_dk.tsv

perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.ctr_lt_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.updn.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.ctr_lt_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.updn.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.ctr_lt_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.updn.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.ctr_lt_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.updn.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.updn.ctr_lt_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.updn.ctr_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.ctr_lt_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.up.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.ctr_lt_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.up.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.ctr_lt_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.up.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.ctr_lt_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.up.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.up.ctr_lt_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.up.ctr_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.ctr_lt_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.dn.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.ctr_lt_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.dn.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.ctr_lt_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.dn.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.ctr_lt_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.dn.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.dn.ctr_lt_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.dn.ctr_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.ctr_lt_0h.ctr_dk_0h.csv genes_med4phm2.tsv > mynoiseqHo.all.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.ctr_lt_1h.ctr_dk_1h.csv genes_med4phm2.tsv > mynoiseqHo.all.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.ctr_lt_2h.ctr_dk_2h.csv genes_med4phm2.tsv > mynoiseqHo.all.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.ctr_lt_4h.ctr_dk_4h.csv genes_med4phm2.tsv > mynoiseqHo.all.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqHo.all.ctr_lt_8h.ctr_dk_8h.csv genes_med4phm2.tsv > mynoiseqHo.all.ctr_lt_8h_vs_dk.tsv

perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.updn.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqPh.updn.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.updn.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqPh.updn.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.updn.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqPh.updn.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.updn.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqPh.updn.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.updn.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqPh.updn.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.up.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqPh.up.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.up.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqPh.up.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.up.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqPh.up.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.up.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqPh.up.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.up.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqPh.up.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.dn.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqPh.dn.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.dn.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqPh.dn.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.dn.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqPh.dn.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.dn.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqPh.dn.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.dn.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqPh.dn.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.all.inf_lt_0h.inf_dk_0h.csv genes_med4phm2.tsv > mynoiseqPh.all.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.all.inf_lt_1h.inf_dk_1h.csv genes_med4phm2.tsv > mynoiseqPh.all.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.all.inf_lt_2h.inf_dk_2h.csv genes_med4phm2.tsv > mynoiseqPh.all.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.all.inf_lt_4h.inf_dk_4h.csv genes_med4phm2.tsv > mynoiseqPh.all.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqMatchDeg.pl mynoiseqPh.all.inf_lt_8h.inf_dk_8h.csv genes_med4phm2.tsv > mynoiseqPh.all.inf_lt_8h_vs_dk.tsv

