perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_8h_vs_ctr.tsv

perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_dk_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_dk_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_dk_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_dk_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_dk_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_dk_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_dk_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_dk_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_dk_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_dk_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_dk_8h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_dk_8h_vs_ctr.tsv

perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.inf_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.inf_lt_8h_vs_dk.tsv

perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.updn.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.updn.ctr_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.up.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.up.ctr_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.dn.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.dn.ctr_lt_8h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.ctr_lt_0h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.ctr_lt_1h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.ctr_lt_2h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.ctr_lt_4h_vs_dk.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHoAs.all.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHoAs.all.ctr_lt_8h_vs_dk.tsv

#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_8h_vs_dk.tsv

