perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_0h.ctr_lt_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_1h.ctr_lt_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_2h.ctr_lt_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_4h.ctr_lt_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_8h.ctr_lt_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_8h_vs_ctr.tsv

perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_dk_0h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_dk_1h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_dk_2h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_dk_4h_vs_ctr.tsv
perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_dk_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_dk_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_dk_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_dk_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_dk_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_dk_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_dk_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_dk_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_dk_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_dk_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_dk_8h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_dk_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_dk_0h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_dk_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_dk_1h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_dk_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_dk_2h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_dk_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_dk_4h_vs_ctr.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_dk_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_dk_8h_vs_ctr.tsv

#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.inf_lt_8h_vs_dk.tsv

#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.updn.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.updn.ctr_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.up.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.up.ctr_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.dn.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.dn.ctr_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.ctr_lt_0h.ctr_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.ctr_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.ctr_lt_1h.ctr_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.ctr_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.ctr_lt_2h.ctr_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.ctr_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.ctr_lt_4h.ctr_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.ctr_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqHo.all.ctr_lt_8h.ctr_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqHo.all.ctr_lt_8h_vs_dk.tsv

#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.updn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.updn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.up.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.up.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.dn.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.dn.inf_lt_8h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_0h.inf_dk_0h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_0h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_1h.inf_dk_1h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_1h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_2h.inf_dk_2h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_2h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_4h.inf_dk_4h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_4h_vs_dk.tsv
#perl ~/scripts/myscripts/noiseqbioMatchDeg.pl mynoiseqPh.all.inf_lt_8h.inf_dk_8h.csv ~/lightdark/bioconductor/genes_med4phm2_latex.tsv > mynoiseqPh.all.inf_lt_8h_vs_dk.tsv

