perl ~/scripts/myscripts/rnaseqIds.pl AAAAAA.txt > Ctr1_Lt_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AACACC.txt > Ctr2_Lt_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AAGAGG.txt > Inf1_Lt_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AATATT.txt > Inf2_Lt_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ACACAC.txt > Ctr1_Dk_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ACCCCG.txt > Ctr2_Dk_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ACGCGT.txt > Inf1_Dk_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ACTCTA.txt > Inf2_Dk_0h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AGAGAG.txt > Ctr1_Lt_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AGCGCT.txt > Ctr2_Lt_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AGGGGA.txt > Inf1_Lt_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl AGTGTC.txt > Inf2_Lt_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ATATAT.txt > Ctr1_Dk_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ATCTCA.txt > Ctr2_Dk_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ATGTGC.txt > Inf1_Dk_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl ATTTTG.txt > Inf2_Dk_1h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CAACCA.txt > Ctr1_Lt_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CACCGC.txt > Ctr2_Lt_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CAGCTG.txt > Inf1_Lt_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CATCAT.txt > Inf2_Lt_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CCAGCC.txt > Ctr1_Dk_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CCCGGG.txt > Ctr2_Dk_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CCGGTT.txt > Inf1_Dk_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CCTGAA.txt > Inf2_Dk_2h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CGATCG.txt > Ctr1_Lt_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CGCTGT.txt > Ctr2_Lt_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CGGTTA.txt > Inf1_Lt_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CGTTAC.txt > Inf2_Lt_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CTAACT.txt > Ctr1_Dk_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CTCAGA.txt > Ctr2_Dk_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CTGATC.txt > Inf1_Dk_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl CTTAAG.txt > Inf2_Dk_4h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GAAGGA.txt > Ctr1_Lt_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GACGTC.txt > Ctr2_Lt_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GAGGAG.txt > Inf1_Lt_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GATGCT.txt > Inf2_Lt_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GCATGC.txt > Ctr1_Dk_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GCCTTG.txt > Ctr2_Dk_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GCGTAT.txt > Inf1_Dk_8h.txt
perl ~/scripts/myscripts/rnaseqIds.pl GCTTCA.txt > Inf2_Dk_8h.txt
