echo "mydeseq2-senseReads6 vs mynoiseq-senseReads6"
echo "****************************** inf_lt_0h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_lt_0h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_lt_0h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_lt_1h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_lt_1h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_lt_1h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_lt_2h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_lt_2h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_lt_2h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_lt_4h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_lt_4h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_lt_4h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_lt_8h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_lt_8h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_lt_8h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_dk_0h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_dk_0h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_dk_0h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_dk_1h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_dk_1h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_dk_1h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_dk_2h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_dk_2h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_dk_2h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_dk_4h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_dk_4h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_dk_4h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
echo "****************************** inf_dk_8h_vs_ctr ******************************"
perl ~/scripts/myscripts/rnaseqCompareTsv2.pl genelist_med4phm2 mydeseq2-senseReads6/mydeseq2Ho.updn.inf_dk_8h_vs_ctr.tsv mynoiseq-senseReads6/mynoiseqHo.updn.inf_dk_8h_vs_ctr.tsv deseq2 noiseq | grep "deseq2.*noiseq"
