htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_1000ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_1000ng_Ribodpl_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_1000ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_1000ng_Ribodpl_R1_rRNA_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_500ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_500ng_Ribodpl_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_500ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_500ng_Ribodpl_R1_rRNA_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_100ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_100ng_Ribodpl_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_100ng_Ribodpl_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_100ng_Ribodpl_R1_rRNA_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_1000ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_1000ng_NoRibo_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_1000ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_1000ng_NoRibo_R1_rRNA_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_500ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_500ng_NoRibo_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_500ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_500ng_NoRibo_R1_rRNA_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t CDS -a 0 ~/vibrio/sam/swt_100ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_100ng_NoRibo_R1_CDS_a0_rev.tsv
htseq-count -f bam -r pos -s reverse -t rRNA -a 0 ~/vibrio/sam/swt_100ng_NoRibo_R1.sorted.bam ~/vibrio/genome/VfES114_fixed.gff > ~/vibrio/bioconductor/swt_100ng_NoRibo_R1_rRNA_a0_rev.tsv
