cat 01b-hit-keg-cat.txt | perl -ne 'chomp; @f = split /\t/; print "$f[1]\n" if $. >= 19' | sort > humann_KOrelAbund.list
cat 04a-hit-keg-mpm-cop-nul-nve-nve-xpe.txt | perl -ne 'chomp; @f = split /\t/; print "$f[1]\n" if $. >= 19' | sort > humann_moduleCoverage.list
cat 04a-hit-keg-mpt-cop-nul-nve-nve-xpe.txt | perl -ne 'chomp; @f = split /\t/; print "$f[1]\n" if $. >= 19' | sort > humann_pathwayCoverage.list
cat 04b-hit-keg-mpm-cop-nul-nve-nve.txt | perl -ne 'chomp; @f = split /\t/; print "$f[1]\n" if $. >= 19' | sort > humann_moduleRelAbund.list
cat 04b-hit-keg-mpt-cop-nul-nve-nve.txt | perl -ne 'chomp; @f = split /\t/; print "$f[1]\n" if $. >= 19' | sort > humann_pathwayRelAbund.list
cat 01b-hit-keg-cat.txt | perl -ne 'chomp; @f = split /\t/; print "$f[0]\t$f[1]\n" if $. >= 19' | sort > humann_KOrelAbund.tsv
cat 04a-hit-keg-mpm-cop-nul-nve-nve-xpe.txt | perl -ne 'chomp; @f = split /\t/; print "$f[0]\t$f[1]\n" if $. >= 19' | sort > humann_moduleCoverage.tsv
cat 04a-hit-keg-mpt-cop-nul-nve-nve-xpe.txt | perl -ne 'chomp; @f = split /\t/; print "$f[0]\t$f[1]\n" if $. >= 19' | sort > humann_pathwayCoverage.tsv
cat 04b-hit-keg-mpm-cop-nul-nve-nve.txt | perl -ne 'chomp; @f = split /\t/; print "$f[0]\t$f[1]\n" if $. >= 19' | sort > humann_moduleRelAbund.tsv
cat 04b-hit-keg-mpt-cop-nul-nve-nve.txt | perl -ne 'chomp; @f = split /\t/; print "$f[0]\t$f[1]\n" if $. >= 19' | sort > humann_pathwayRelAbund.tsv
