perl ~/scripts/myscripts/rename.pl 's/AAAAAA/Ctr1_Lt_0h/' AAAAAA.txt
perl ~/scripts/myscripts/rename.pl 's/AACACC/Ctr2_Lt_0h/' AACACC.txt
perl ~/scripts/myscripts/rename.pl 's/AAGAGG/Inf1_Lt_0h/' AAGAGG.txt
perl ~/scripts/myscripts/rename.pl 's/AATATT/Inf2_Lt_0h/' AATATT.txt
perl ~/scripts/myscripts/rename.pl 's/ACACAC/Ctr1_Dk_0h/' ACACAC.txt
perl ~/scripts/myscripts/rename.pl 's/ACCCCG/Ctr2_Dk_0h/' ACCCCG.txt
perl ~/scripts/myscripts/rename.pl 's/ACGCGT/Inf1_Dk_0h/' ACGCGT.txt
perl ~/scripts/myscripts/rename.pl 's/ACTCTA/Inf2_Dk_0h/' ACTCTA.txt
perl ~/scripts/myscripts/rename.pl 's/AGAGAG/Ctr1_Lt_1h/' AGAGAG.txt
perl ~/scripts/myscripts/rename.pl 's/AGCGCT/Ctr2_Lt_1h/' AGCGCT.txt
perl ~/scripts/myscripts/rename.pl 's/AGGGGA/Inf1_Lt_1h/' AGGGGA.txt
perl ~/scripts/myscripts/rename.pl 's/AGTGTC/Inf2_Lt_1h/' AGTGTC.txt
perl ~/scripts/myscripts/rename.pl 's/ATATAT/Ctr1_Dk_1h/' ATATAT.txt
perl ~/scripts/myscripts/rename.pl 's/ATCTCA/Ctr2_Dk_1h/' ATCTCA.txt
perl ~/scripts/myscripts/rename.pl 's/ATGTGC/Inf1_Dk_1h/' ATGTGC.txt
perl ~/scripts/myscripts/rename.pl 's/ATTTTG/Inf2_Dk_1h/' ATTTTG.txt
perl ~/scripts/myscripts/rename.pl 's/CAACCA/Ctr1_Lt_2h/' CAACCA.txt
perl ~/scripts/myscripts/rename.pl 's/CACCGC/Ctr2_Lt_2h/' CACCGC.txt
perl ~/scripts/myscripts/rename.pl 's/CAGCTG/Inf1_Lt_2h/' CAGCTG.txt
perl ~/scripts/myscripts/rename.pl 's/CATCAT/Inf2_Lt_2h/' CATCAT.txt
perl ~/scripts/myscripts/rename.pl 's/CCAGCC/Ctr1_Dk_2h/' CCAGCC.txt
perl ~/scripts/myscripts/rename.pl 's/CCCGGG/Ctr2_Dk_2h/' CCCGGG.txt
perl ~/scripts/myscripts/rename.pl 's/CCGGTT/Inf1_Dk_2h/' CCGGTT.txt
perl ~/scripts/myscripts/rename.pl 's/CCTGAA/Inf2_Dk_2h/' CCTGAA.txt
perl ~/scripts/myscripts/rename.pl 's/CGATCG/Ctr1_Lt_4h/' CGATCG.txt
perl ~/scripts/myscripts/rename.pl 's/CGCTGT/Ctr2_Lt_4h/' CGCTGT.txt
perl ~/scripts/myscripts/rename.pl 's/CGGTTA/Inf1_Lt_4h/' CGGTTA.txt
perl ~/scripts/myscripts/rename.pl 's/CGTTAC/Inf2_Lt_4h/' CGTTAC.txt
perl ~/scripts/myscripts/rename.pl 's/CTAACT/Ctr1_Dk_4h/' CTAACT.txt
perl ~/scripts/myscripts/rename.pl 's/CTCAGA/Ctr2_Dk_4h/' CTCAGA.txt
perl ~/scripts/myscripts/rename.pl 's/CTGATC/Inf1_Dk_4h/' CTGATC.txt
perl ~/scripts/myscripts/rename.pl 's/CTTAAG/Inf2_Dk_4h/' CTTAAG.txt
perl ~/scripts/myscripts/rename.pl 's/GAAGGA/Ctr1_Lt_8h/' GAAGGA.txt
perl ~/scripts/myscripts/rename.pl 's/GACGTC/Ctr2_Lt_8h/' GACGTC.txt
perl ~/scripts/myscripts/rename.pl 's/GAGGAG/Inf1_Lt_8h/' GAGGAG.txt
perl ~/scripts/myscripts/rename.pl 's/GATGCT/Inf2_Lt_8h/' GATGCT.txt
perl ~/scripts/myscripts/rename.pl 's/GCATGC/Ctr1_Dk_8h/' GCATGC.txt
perl ~/scripts/myscripts/rename.pl 's/GCCTTG/Ctr2_Dk_8h/' GCCTTG.txt
perl ~/scripts/myscripts/rename.pl 's/GCGTAT/Inf1_Dk_8h/' GCGTAT.txt
perl ~/scripts/myscripts/rename.pl 's/GCTTCA/Inf2_Dk_8h/' GCTTCA.txt